### ISSUE TITLE
 启动报错 

### ISSUE THREAD

**Issue by houzaicunsky** [gojuukaze/liteAuth#3]
始化完成
(liteAuth_env) [root@BJ-pub-ldap liteAuth]# ./lite_auth.py start
启动LDAP Server
Unhandled Error
Traceback (most recent call last):
  File "/opt/liteAuth_env/lib64/python3.6/site-packages/twisted/application/app.py", line 676, in run
    runApp(config)
  File "/opt/liteAuth_env/lib64/python3.6/site-packages/twisted/scripts/twistd.py", line 30, in runApp
    runner.run()
  File "/opt/liteAuth_env/lib64/python3.6/site-packages/twisted/application/app.py", line 372, in run
    self.application = self.createOrGetApplication()
  File "/opt/liteAuth_env/lib64/python3.6/site-packages/twisted/application/app.py", line 439, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/opt/liteAuth_env/lib64/python3.6/site-packages/twisted/application/app.py", line 448, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/opt/liteAuth_env/lib64/python3.6/site-packages/twisted/application/service.py", line 404, in loadApplication
    application = sob.loadValueFromFile(filename, "application")
  File "/opt/liteAuth_env/lib64/python3.6/site-packages/twisted/persisted/sob.py", line 176, in loadValueFromFile
    eval(codeObj, d, d)
  File "twisted_config.py", line 12, in <module>
    from lite_auth_ldap.service import LiteAutLDAPService
  File "/data/liteAuth/lite_auth_ldap/service.py", line 4, in <module>
    from lite_auth_ldap.factory import LiteAuthLDAPFactory
  File "/data/liteAuth/lite_auth_ldap/factory.py", line 3, in <module>
    from lite_auth_ldap.handler import LiteAuthHandler
  File "/data/liteAuth/lite_auth_ldap/handler.py", line 7, in <module>
    from lite_auth_ldap.manager import json_post, filter_object_to_str
  File "/data/liteAuth/lite_auth_ldap/manager.py", line 3, in <module>
    import treq
  File "/opt/liteAuth_env/lib64/python3.6/site-packages/treq/__init__.py", line 5, in <module>
    from treq.api import head, get, post, put, patch, delete, request
  File "/opt/liteAuth_env/lib64/python3.6/site-packages/treq/api.py", line 5, in <module>
    from treq.client import HTTPClient
  File "/opt/liteAuth_env/lib64/python3.6/site-packages/treq/client.py", line 11, in <module>
    from twisted.python.compat import _PY3, unicode
builtins.ImportError: cannot import name '_PY3'

Failed to load application: cannot import name '_PY3'

[错误]：启动失败

**Comment by houzaicunsky** [comment]
docker  镜像的镜像也不存在了。。。

**Comment by gojuukaze** [comment]
这个应该是py版本问题，你换3.7或者3.8试试。  

另外docker镜像是在的（ https://hub.docker.com/repository/docker/gojuukaze/liteauth ），你应该是用来代理加速吧，你把代理注释掉试试

**Comment by houzaicunsky** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    您好：         我已经用  docker启动起来了 
        
    
        jumper 我该怎么配置呢？
        
    
     
    
        
                    ***@***.***
        
    
    
        签名由网易邮箱大师定制
    
 

    在2021年10月15日 ***@***.***> 写道： 




这个应该是py版本问题，你换3.7或者3.8试试。

另外docker镜像是在的（https://hub.docker.com/repository/docker/gojuukaze/liteauth），你应该是用来代理加速吧，你把代理注释掉试试

**Comment by houzaicunsky** [comment]
LDAP 服务器
LDAP 地址
ldap://172.*:8389
如: ldap://localhost:389
绑定 DN
uid=ldap
密码
••••••••••
LDAP 用户
用户 OU
ou=tech,dc=jumpserver,dc=org
多个 OU 使用 | 分割
用户过滤器
(cn=%(user)s)
可能的选项是(cn或uid或sAMAccountName=%(user)s)
用户属性映射
{"username":"cn","name":"sn","email":"mail"}
用户属性映射代表怎样将LDAP中用户属性映射到jumpserver用户上，username, name,email 是jumpserver的用户需要属性
****
 

jump 我该咋配置

**Comment by gojuukaze** [comment]
* 绑定DN: uid=ldap
* 密码: ********
* 用户OU: 为空或ou=user
* 用户过滤器:	(&(groups=jumpserver)(uid=%(user)s))
* LADP属性映射:	{"username": "uid", "name": "name", "email": "mail"}

----
你这样配试试

**Comment by houzaicunsky** [comment]
DN 一定要是完整的DN，不能跳过OU，可以使用其他工具查询
cn=admin,ou=aaa,dc=jumpserver,dc=org 或者用 user@domain.com 形式

用户OU 用户OU可以只写顶层OU，不写子OU
ou=aaa,ou=bbb,ou=ccc,dc=jumpserver,dc=org，可以只写 ou=ccc,dc=jumpserver,dc=org

用户过滤器 根据规则到 用户OU 里面去检索用户，支持 memberof
(uid=%(user)s) 或 (sAMAccountName=%(user)s)

LADP属性映射 username name email 这三项不可修改删除
{"username": "uid", "name": "sn", "email": "mail"} 或 {"username": "sAMAccountName", "name": "cn", "email": "mail"}

注意：用户过滤器用什么筛选，LDAP属性映射字段要与其一致，过滤器用 uid，LDAP属性映射也要用 uid 


官方这么要求的。

**Comment by gojuukaze** [comment]
这些都是ldap请求的参数多个少个无所谓。官方那个要求是标准的ldap配置，这个项目简化了很多，没有sn，ou这些东西。

只要能正常登录就行了

**Comment by gojuukaze** [comment]
如果不了解ldap，你可以先看看这个 https://doc.ikaze.cn/liteauth/ldap/index.html

**Comment by feko2018** [comment]
普通安装方法启动，也有这个问题，已经解决，Twisted版本问题，python3.6虚拟环境下[安装](https://blog.51cto.com/feko/4778753)pip install Twisted==20.3.0
