### ISSUE TITLE
LDAP会在硬盘延迟较高时超时失败

### ISSUE THREAD

**Issue by TsFreddie** [gojuukaze/liteAuth#6]
随机报错，无论是ldap还是user的dn都是同样的错误。运气好的话可以查询出一次，但其他时候都是报错。

之前用了一周没什么问题，然后今天docker重启了一次就这样了。

```
2022-01-19T04:09:22+0000 [LiteAuthLDAPServer,21,172.17.0.1] S<-C LDAPMessage(id=3, value=LDAPBindRequest(version=3, dn='uid=XXX', auth='********************', sasl=False), controls=None)
2022-01-19T04:09:25+0000 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	--- <exception caught here> ---
	  File "/usr/local/lib/python3.8/dist-packages/twisted/internet/defer.py", line 654, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/local/lib/python3.8/dist-packages/ldaptor/protocols/ldap/ldapserver.py", line 92, in _cbLDAPError
	    reason.trap(ldaperrors.LDAPException)
	  File "/usr/local/lib/python3.8/dist-packages/twisted/python/failure.py", line 460, in trap
	    self.raiseException()
	  File "/usr/local/lib/python3.8/dist-packages/twisted/python/failure.py", line 488, in raiseException
	    raise self.value.with_traceback(self.tb)
	twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.defer.CancelledError: >]
```

**Comment by TsFreddie** [comment]
删掉docker容器用新镜像启动一个就好了

**Comment by TsFreddie** [comment]
重新打开下，之前因为NAS在重建数据，硬盘的响应速度比较慢。LDAP在这种情况下似乎会超时。不知道能不能将超时的上限稍微拉高一些甚至做成可配置项？

**Comment by gojuukaze** [comment]
你可以调大 ``LDAP_API_TIMEOUT`` 与 ``LDAP_API_AUTH_EXPIRY`` 
具体说明见 https://doc.ikaze.cn/liteauth/config.html#LDAP_API_TIMEOUT

**Comment by TsFreddie** [comment]
似乎是我眼瞎了(( 感谢
